config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
  resources :tasks do
    collection do
      post :confirm
    end
  end
end
# post '/admin/users/new', to: 'admin/users#create'
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
    has_many :labellings, dependent: :destroy
    has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :name, presence: true
    validates :detail, presence: true
    has_many :labellings, dependent: :destroy
    has_many :labels,through: :labellings

    enum status:{
       未着手:0, 着手中:1, 完了:2 
    }

    enum priority:{
       高:0, 中:1, 低:2 
    }
    
    scope :name_search, -> (name) { where('name LIKE ?', "%#{name}%")}
    scope :status_search, -> (status) { where(status: status)}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tasks, dependent: :destroy
    before_destroy:admin_jump
    before_update:admin_jump
    
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum: 6 },on: :new

    private

    def admin_jump
        throw(:abort) if self.admin == true && User.where(admin: true).count == 1
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    before_action :admin_user_current

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザーを作成しました'
    else
      render :new
   end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to admin_users_path, notice: 'ユーザー編集しました'
    else
        render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除しました'
    else
      redirect_to admin_users_path , notice: 'ユーザー削除できませんでした'
    end  
  end


  private
  
  def admin_user_current
     redirect_to tasks_path, notice: '管理者以外はアクセスできません'  unless current_user.admin? 
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :login_required
   
    
    private

    def login_required
        redirect_to new_session_path unless current_user
    end

    def current_login?
        redirect_to tasks_path if logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :current_login?, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy]
  def new
    @task = Task.new
  end

  def index
    @tasks = current_user.tasks.order(created_at: "DESC").page(params[:page]).per(10)
    if params[:sort_expired].present?
      @tasks = @tasks.order(termination_date: "DESC")
    end

    if params[:sort_priority].present?
      @tasks = @tasks.order(priority: "ASC")
    # else
    #   @tasks = Task.all.order(created_at: "DESC")
    end

    if params[:task].present?
      if params[:task][:name].present? && params[:task][:status].present?
        @tasks = @tasks.name_search(params[:task][:name]).status_search(params[:task][:status])
      elsif params[:task][:name].present?
        @tasks = @tasks.name_search(params[:task][:name])
      elsif params[:task][:status].present?
        @tasks = @tasks.status_search(params[:task][:status])
      elsif params[:task][:label_id].present?
        @tasks = @tasks.where(id: Labelling.where(label_id: params[:task][:label_id]).pluck(:task_id))

      else
        @tasks
      end
    end
  end

def create
    @task = current_user.tasks.build(task_params)
      if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path(@task)
        flash[:notice] = "作成しました"
      else
        render :new
      end
    end
  end 
    
  def show
    Task.find(params[:id]) 
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
      flash[:notice] =  "編集しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
    flash[:notice] = "削除しました"
  end

  def confirm
    @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private

  def task_params
    params.require(:task).permit(:name, :detail, :termination_date, :status, :priority, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    before_action :current_login?, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user.id) 
        else
          render new_user_path
        end
    end

    def show
        @user = User.find(params[:id])
        @tasks = current_user.tasks
        unless @user == current_user
            redirect_to tasks_path
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'create'
          confirm_tasks_path
        elsif action_name == 'edit'
          task_path
        end
      end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :名前 %>
    <%= f.text_field :name %>
 
    <%= f.label :メールアドレス %>
    <%= f.email_field :email %>

    <%= f.label :管理者権限 %>
    <%= f.check_box :admin  %>
 
    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/admin/users/index.html.erb
<h1>一覧画面（管理者用）</h1>

<table>
  <tr>
    <th>名前</th>
    <th>メールアドレス</th>
    <th>タスク登録数</th>
    <th>管理者権限</th>
   </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.tasks.count %></td>
    <td><% if user.admin?  %>
    <p>管理者</p>
    <% else  %>
    <p>一般ユーザー</p>
    <% end %></td>
    <td><%= link_to '詳細を確認する', admin_user_path(user.id) %></td>
    <td><%= link_to "ユーザーを編集する", edit_admin_user_path(user.id) %></td>
    <td><%= link_to "ユーザーを削除する", admin_user_path(user.id), method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'ユーザー追加', new_admin_user_path %>

app/views/admin/users/new.html.erb
<%= form_with(model:[:admin,@user], local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :名前 %>
    <%= f.text_field :name %>
 
    <%= f.label :メールアドレス %>
    <%= f.email_field :email %>
 
 
    <%= f.label :管理者権限 %>
    <%= f.check_box :admin, {},true, false  %>
 

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

  <%= f.submit %>
<% end %>

app/views/admin/users/show.html.erb
<h1>詳細画面(管理者用)</h1>
<p>タイトル: <%= @user.name %></p>
<p>内容: <%= @user.email %></p>

<%= link_to '戻る', admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EducationalTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>


    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% if current_user.admin?  %>
      <%= link_to "管理者画面へ", admin_users_path %>
      <% end %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true, url: choose_new_or_edit  ) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= @task.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_name">
    <%= form.label "名前"%>
    <%= form.text_field :name %>
  </div>
  <div class="task_detail">
    <%= form.label "詳細" %>
    <%= form.text_area :detail %>
  </div>
  <div class="task_detail">
    <%= form.label "日付" %>
    <%= form.date_field :termination_date %>
  </div>
  <div>
    <%= form.label "status" %>
    <%= form.select :status, Task.statuses.keys.to_a, {} %>
  </div>
  <div>
    <%= form.label "priority" %>
    <%= form.select :priority, Task.priorities.keys.to_a, {} %>
  </div>

   <div>
    <%= form.label "label" %>
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to '一覧画面に戻る', tasks_path %>

app/views/tasks/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @task, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :detail %>
  <%= form.hidden_field :termination_date %>
  <%= form.hidden_field :status %>
  <%= form.hidden_field :priority %>
  <%
=begin%>
 <%= form.hidden_field :label.name %> 
<%
=end%>
  <% @task.labels.each do |label| %> 
    <%= form.hidden_field :label_ids, multiple: true, value: label.id %> 
  <% end %> 
  <%
=begin%>
 <%= form.hidden_field :label_ids, multiple: true %> 
<%
=end%>
 


  <p>名前:<%= @task.name %></p>
  <p>詳細:<%= @task.detail %></p>
  <p>日付:<%= @task.termination_date %></p>
  <p>ステータス:<%= @task.status %></p>
  <p>優先順:<%= @task.priority %></p>            
  <p>優先順:<%= @task.label_ids %></p>           
  <%= form.submit  "登録する" %>

  <%= form.submit '戻る', name: 'back' %>
<% end %>

app/views/tasks/edit.html.erb
  <h2>編集する</h2>

  <%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>日付</th>
    <th>ステータス</th>
    <th>優先度</th>
    <th>ユーザー名</th>
    <th>ラベル</th>

  </tr>
<%= form_with(url:tasks_path, local: true,   scope: :task, method: :get) do |f| %>
<%= f.select("label_id", Label.all.pluck(:name, :id), { include_blank: true })%>
<%= f.submit 'Search', name: nil %>

  <div class="title_name">
    <%= f.label "名前" %>
    <%= f.text_field :name, class:"rform-control" %>
    <%= f.select :status, Task.statuses.keys.to_a, { include_blank: "選択してください" } %>
  </div><br>
  <%= f.submit "検索" %>
<% end %>

<% @tasks.each do |task| %>
  <tr class = task_list>
    <td><%= task.name %></td>
    <td><%= task.detail %></td>
    <td><%= task.termination_date %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.user.name %></td>
    
    <td><% task.labels.each do |label| %>  
        <%= label.name %>
        <% end %>
    </td>

    <td><%= link_to '詳細を確認する', task_path(task.id), class:"btn btn-primary" %></td>
    <td><%= link_to "編集する", edit_task_path(task.id), class:"btn btn-success" %></td>
    <td><%= link_to "削除する", task_path(task.id), method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>


<%= link_to '新しくタスクを投稿する', new_task_path %>
<th><%= link_to "終了期限でソートする", tasks_path(sort_expired:"true") %></th>
<th><%= link_to "優先順", tasks_path(sort_priority: "true") %></th>

app/views/tasks/new.html.erb
  <h2>作成する</h2>

  <%= render 'form' %>

app/views/tasks/show.html.erb
<h1>詳細画面</h1>
<p>名前: <%= @task.name %></p>
<p>詳細: <%= @task.detail %></p>
<p>詳細: <%= @task.termination_date %></p>
<p>詳細: <%= @task.status %></p>
<p>詳細: <%= @task.priority %></p>

<%= link_to '戻る', tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "送信" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<table>
<tr>
    <th>タイトル</th>
    <th>内容</th>
    <th>日付</th>
    <th>ステータス</th>
    <th>優先度</th>
    <th>ユーザー名</th>
  </tr>

<% @tasks.each do |task| %>
  <tr class = task_list>
    <td><%= task.name %></td>
    <td><%= task.detail %></td>
    <td><%= task.termination_date %></td>
    <td><%= task.status %></td>
    <td><%= task.priority %></td>
    <td><%= task.user.name %></td>
    <td><%= link_to '詳細を確認する', task_path(task.id), class:"btn btn-primary" %></td>
    <td><%= link_to "編集する", edit_task_path(task.id), class:"btn btn-success" %></td>
    <td><%= link_to "削除する", task_path(task.id), method: :delete, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>
<%= link_to 'タスク一覧', tasks_path %>